### ISSUE TITLE
How to 

### ISSUE THREAD

**Issue by sabahudin8989** [stop-piracy/skyit-free#1]
how do i find the license for sky it  and pssh

**Comment by stop-piracy** [comment]
You just have to go to the bottom of readme and open the URLs with Microsoft Edge. You'll be able to watch the streams using bitmovin players without any license.

Incase you want to play Smooth Streaming content without using an online player, I might post a script in future but it's not planned.

**Comment by sabahudin8989** [comment]
could you share the method

**Comment by stop-piracy** [comment]
I wont disclosure how to grab the keys because I am not promoting piracy, but soon I will disclose the report between me and Sky.
There you will understand that the keys are grabbed using a Widevine license url, not PlayReady
